#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser

unamestr=`uname`

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi


# my exports

PHPENV_VERSION=7.4
GO_LANG_VERSION=1.20.4

export M2_HOME=~/dev_tools/apache-maven
export RVM_HOME=$HOME/.rvm/bin
export COMPOSER_HOME=~/.composer/vendor/bin
export ACTIVATOR_HOME=~/Documents/dev_tools/activator
export WORK_APPS_HOME=~/dev_tools/work
export BDUTIL_HOME=~/Documents/dev_tools/bdutil
export GVM_ROOT=~/.gvm
export GVM_BIN=~/.gvm/bin
export PYENV_ROOT=~/.pyenv
export PHPENV_HOME=~/.phpenv/bin
export PHPROOT_HOME=~/.phpenv/versions/${PHPENV_VERSION}/bin


if [[ "$unamestr" == 'Darwin' ]]; then
  # override golang version
  GO_LANG_VERSION=1.20
  export GOPLS_HOME=~/.gvm/pkgsets/go${GO_LANG_VERSION}/global/bin
  export GO_HOME=~/.gvm/gos/go${GO_LANG_VERSION}/bin

  if [ -x brew ]; then
    BREW_HOME=$(brew --prefix)
  fi

  # gnu-sed
  export GNU_SED_HOME="${BREW_HOME}/opt/gnu-sed/libexec/gnubin"
  # gnu-tar
  export GNU_TAR_HOME="${BREW_HOME}/opt/gnu-tar/libexec/gnubin"
  # gnu-which
  export GNU_WHICH_HOME="${BREW_HOME}/opt/gnu-which/libexec/gnubin"
  # grep
  export GNU_GREP_HOME="${BREW_HOME}/opt/grep/libexec/gnubin"
else
  export GOPLS_HOME=~/.gvm/pkgsets/go${GO_LANG_VERSION}/global/bin
  export GO_HOME=~/.gvm/gos/go${GO_LANG_VERSION}/bin
fi


#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  ${M2_HOME}/bin
  ${COMPOSER_HOME}
  ${RVM_HOME}
  ${ACTIVATOR_HOME}
  ${WORK_APPS_HOME}
  ${path}
  ${BDUTIL_HOME}
  ${GO_HOME}
  ${PYENV_ROOT}
  ${PHPENV_HOME}
  ${PHPROOT_HOME}
  ${GVM_ROOT}
  ${GVM_BIN}
)

if [[ "$unamestr" == 'Darwin' ]]; then
  path+=(
    ${GNU_SED_HOME}
    ${GNU_TAR_HOME}
    ${GNU_WHICH_HOME}
    ${GNU_GREP_HOME}
  )
fi

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

#
# Temporary Files
#

if [[ ! -d "$TMPDIR" ]]; then
  export TMPDIR="/tmp/$USER"
  mkdir -p -m 700 "$TMPDIR"
fi

TMPPREFIX="${TMPDIR%/}/zsh"
if [[ ! -d "$TMPPREFIX" ]]; then
  mkdir -p "$TMPPREFIX"
fi
