# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINES =
    {
        "ubuntu" =>
            {:box => "hashicorp/precise64",
             :provision => "bootstrap-deb.sh",
             :type => "groupby"
            },
        "centos" =>
            {:box => "chef/centos-6.5",
             :provision => "bootstrap-rhel.sh",
             :type => "groupby"
            },
        "laravel" =>
            {:box => "laravel/homestead",
             :provision => "bootstrap-laravel.sh",
             :type => "homestead"
            },
        "nginx" =>
            {:box => "precise32",
             :provision => "bootstrap-nginx.sh",
             :type => "nginx"
            },
        "docker" =>
            {:box => "chef/centos-6.5",
             :provision => "bootstrap-docker.sh"
            },
    }

VAGRANTFILE_API_VERSION = "2"
path = "#{File.dirname(__FILE__)}"

require 'yaml'
require path + '/laravel/scripts/homestead.rb'
require path + '/node-nginx-cluster/scripts/nginx.rb'

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  MACHINES.each_pair do |name, opts|
    config.vm.define name do |c|
      c.vm.box = opts[:box]
      c.vm.provision :shell, :path => opts[:provision]
      if opts[:type] == "groupby"
        config.vm.provider "virtualbox" do |v|
          v.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
          v.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
        end
        c.vm.network "forwarded_port", guest: 10060, host: 10077  # bridge admin port
        c.vm.network "forwarded_port", guest: 14993, host: 14999  # command center
        c.vm.network "forwarded_port", guest: 27017, host: 27020  # mongo port
        c.vm.network "forwarded_port", guest: 80, host: 8888      # nginx port
      elsif opts[:type] == "personal"
        c.vm.network "forwarded_port", guest: 8080, host: 9090 # laravel port
      elsif opts[:type] == "homestead"
        Homestead.configure(config, YAML::load(File.read(path + '/laravel/Homestead.yaml')))
      elsif opts[:type] == "nginx"
        Nginx.configure(config)
      end
    end
  end
end
# 10.0.2.2 