---

elasticsearch:
  image: elasticsearch:5-alpine
  ports:
    - "9200:9200"
    - "9300:9300"
  command: elasticsearch -Escript.inline=true -Ehttp.cors.enabled=true -Ehttp.cors.allow-origin=*
  volumes:
    - '/opt/esdata:/usr/share/elasticsearch/data'
rabbitmq:
  image: rabbitmq:3-management-alpine
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    - RABBITMQ_HIPE_COMPILE=1
redis:
  image: redis:alpine
  ports:
    - "6379:6379"
  volumes:
    - /opt/redis:/data
  command: redis-server --appendonly yes --notify-keyspace-events Ex