---

#elasticsearch:
#  image: ferronrsmith/elasticsearch:alpine
#  ports:
#    - "9201:9200"
#    - "9301:9300"
rabbitmq:
  image: smebberson/alpine-rabbitmq
  ports:
    - "5672:5672"
    - "15672:15672"
  environment:
    - RABBITMQ_ENABLE_MANAGEMENT_PLUGIN=true
    - RABBITMQ_LOOPBACK_USERS=[]
weedfs:
  image: ferronrsmith/seaweedfs
  ports:
    - "9333:9333"
    - "8080:8080"
  volumes:
   - /opt/weedfs/data:/data
  command: server -dir="/data"
redis:
  image: redis:alpine
  ports:
    - "6379:6379"
  volumes:
    - /opt/redis:/data
  command: redis-server --appendonly yes
